name: flutter_app5
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  moor_flutter: ^4.0.0
  provider: ^5.0.0
  moor_inspector: ^0.2.0
  responsive_framework: ^0.1.0
  flutter_svg: ^0.22.0
  multi_select_flutter: ^4.0.0
  beamer: ^0.13.3
  collection: ^1.15.0-nullsafety.4
  timeago: ^3.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  moor_generator: ^4.3.0




flutter:

  uses-material-design: true
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo_SemiBold.ttf
    - family: righteous_regular
      fonts:
        - asset: assets/fonts/Righteous_Regular.ttf
  assets:
    - assets/images/

